## Experiments

In [1]:
from Lie_algebras import *
import numpy as np

### Task: check find algrebra smaller than complete

In [26]:
# define operators for H: Z1+Z2+Z3, X1X2+X2X3+X3X1
n = 3
ops = [sum([tensor(Z, n, i) for i in range(n)]), sum([tensor(X, n, i)@tensor(X, n, (i+1)%n) for i in range(n)])]

# define opertaor for I: Z1Z3
t = [tensor(Z, 3, 0)@tensor(Z, 3, 2)]

In [27]:
falg = find_algebra(t, ops, 20)
calg = complete_algebra(ops + t, 20)
print(f"calg length = {len(calg)}; falg length = {len(falg)}")

calg length = 18; falg length = 4


### Task: given A, find B such that [A, B] = 0

In [53]:
def find_comm(n):
    # random nxn matrix
    Re = np.random.randn(n, n)
    Im = np.random.randn(n, n)
    A = Re + 1.j * Im

    # find eigenvectors of A tensor A^-T with eigenvalue 1 (some error when finding evals=1 so -1 and allow 1e-6 error about 0)
    L = np.kron(A, np.linalg.inv(A).T)
    l, V = np.linalg.eig(L)
    l -= 1
    l = l.real**2 + l.imag**2
    ii = (l<1e-6)
    v = V[:, ii]

    # construct B by reshape eigenvectors
    for vec in v.T:
        B = vec.reshape(n, n)
        # raise error if AB-BA is not 0
        C = comm(B, A)
        assert np.allclose(C, 0)

    # return the number of Bs found

    return v.shape[1]

In [46]:
[find_comm(i) for i in range(1, 26)]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [52]:
find_comm(2)

[[-0.36960898-0.53607787j  0.11445961-0.84934057j]
 [ 0.93584564-0.85089595j -0.44441963+0.39588458j]]


2

### Task: given A_n, find B such that [A_n, B] = 0 for all n

In [1]:
# helppp not possible...

### Task: decompose a given operator into a sum of Pauli operators (+using Pauli class??)

In [3]:
decomp = decompose(A)
decomp

([0.5, 0.5, -0.5j, 0.5],
 [array([[1., 0.],
         [0., 1.]]),
  array([[0, 1],
         [1, 0]]),
  array([[ 0.+0.j, -0.-1.j],
         [ 0.+1.j,  0.+0.j]]),
  array([[ 1,  0],
         [ 0, -1]])])

In [4]:
np.allclose(decomp[0][0] * I + decomp[0][1] * X + decomp[0][2] * Y + decomp[0][3] * Z, A)

True

In [5]:
test_decomp = tensor(B, 3, 0, 1)
decomp1 = decompose(test_decomp)

In [6]:
tested_decomp = np.zeros(test_decomp.shape)
for i in range(test_decomp.shape[0]**2):
    tested_decomp = tested_decomp + decomp1[0][i] * decomp1[1][i]
np.allclose(tested_decomp, test_decomp)

True