## Experiments

In [1]:
from Lie_algebras import *
import numpy as np

### Messing about with finding algebras

In [3]:
# general n
n = 3
ops1, ops2 = [], []
for i in range(n):
    new_op = [I for i in range(n)]
    new_op[i] = Z
    ops1.append(new_op)
for i in range(n):
    new_op = [I for i in range(n)]
    new_op[i] = X
    new_op[(i+1)%n] = X
    ops2.append(new_op)
op1 = Pauli(ops1[0])
op2 = Pauli(ops2[0])
for j in range(1, len(ops1)):
    op1 += Pauli(ops1[j])
for j in range(1, len(ops2)):
    op2 += Pauli(ops2[j])

ops3 = [I for i in range(n)]
ops3[0], ops3[n-1] = X, Y
op3 = Pauli(ops3)

alg = pauli_find_algebra([op3], [op1, op2], 30)
alg_full = pauli_complete_algebra([op1, op2], 30)
print("Full algebra:")
print(len(alg_full))
print(alg_full)
print("Hopefully smaller algebra:")
print(len(alg))
print(alg)

Full algebra:
8
[SuperPauli([(1, Pauli([Z, I, I])), (1, Pauli([I, Z, I])), (1, Pauli([I, I, Z]))]), SuperPauli([(1, Pauli([X, X, I])), (1, Pauli([I, X, X])), (1, Pauli([X, I, X]))]), SuperPauli([(2j, Pauli([Y, X, I])), (2j, Pauli([Y, I, X])), (2j, Pauli([X, Y, I])), (2j, Pauli([I, Y, X])), (2j, Pauli([I, X, Y])), (2j, Pauli([X, I, Y]))]), SuperPauli([((8+0j), Pauli([X, X, I])), ((8+0j), Pauli([X, I, X])), ((-8+0j), Pauli([Y, Y, I])), ((-8+0j), Pauli([Y, I, Y])), ((8+0j), Pauli([I, X, X])), ((-8+0j), Pauli([I, Y, Y]))]), SuperPauli([((-8+0j), Pauli([Z, I, I])), ((-8+0j), Pauli([Z, X, X])), ((-8+0j), Pauli([I, Z, I])), ((-8+0j), Pauli([X, Z, X])), ((-8+0j), Pauli([I, I, Z])), ((-8+0j), Pauli([X, X, Z]))]), SuperPauli([((-0-16j), Pauli([Y, Z, X])), ((-0-16j), Pauli([Y, X, Z])), ((-0-16j), Pauli([Z, Y, X])), ((-0-16j), Pauli([X, Y, Z])), ((-0-16j), Pauli([Z, X, Y])), ((-0-16j), Pauli([X, Z, Y]))]), SuperPauli([((128+0j), Pauli([Z, I, I])), ((64+0j), Pauli([Z, X, X])), ((128+0j), Pauli([I, 

In [6]:
%timeit pauli_find_algebra([op3], [op1, op2], 20)

152 ms ± 19.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
%timeit pauli_find_algebra([op3], [op1, op2], 20)

80.5 ms ± 1.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit pauli_find_algebra([op3], [op1, op2], 20)

41.5 ms ± 430 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
pauli_find_algebra([Pauli([X]), Pauli([Y])], [Pauli([Z])], 30)

[SuperPauli([(1, Pauli([X]))]),
 SuperPauli([(1, Pauli([Y]))]),
 SuperPauli([(2j, Pauli([Z]))])]

In [7]:
op1 = Pauli([X, X, I, I])
op2 = Pauli([X, I, X, I])
op3 = Pauli([X, I, I, X])
op4 = Pauli([I, X, X, I])
op5 = Pauli([I, I, X, X])
op5 = Pauli([Z, I, I, I]) + Pauli([I, Z, I, I]) + Pauli([I, I, Z, I]) + Pauli([I, I, I, Z])

com = pauli_complete_algebra([op1, op2, op3, op4, op5], 200)
len(com)

fin = pauli_find_algebra([op5], [op1, op2, op3, op4, op5], 200)
len(fin)

64

In [8]:
len(com)

126

: 

In [5]:
len(com)

3

### Task: Testing $g_1$ algebra from paper (with timing)

In [11]:
op1 = Pauli([X, Y, I])
op2 = Pauli([I, X, Y])
op4 = Pauli([Y, I, X])
op3 = Pauli([I, Z, Z])
pau3 = pauli_complete_algebra([op1, op2, op3, op4], 20)
len(pau3)

12

In [12]:
pau3

[SuperPauli([(1, Pauli([X, Y, I]))]),
 SuperPauli([(1, Pauli([I, X, Y]))]),
 SuperPauli([(1, Pauli([I, Z, Z]))]),
 SuperPauli([(1, Pauli([Y, I, X]))]),
 SuperPauli([(-2j, Pauli([X, Z, Y]))]),
 SuperPauli([(2j, Pauli([X, X, Z]))]),
 SuperPauli([(2j, Pauli([Z, Y, X]))]),
 SuperPauli([(-2j, Pauli([Y, X, Z]))]),
 SuperPauli([(2j, Pauli([Y, Z, Y]))]),
 SuperPauli([((-4+0j), Pauli([X, I, X]))]),
 SuperPauli([((4+0j), Pauli([Y, Y, I]))]),
 SuperPauli([(8j, Pauli([Z, I, I]))])]

In [45]:
op1 = Pauli([X, Y, I, I, I, I])
op2 = Pauli([I, X, Y, I, I, I])
op3 = Pauli([I, I, X, Y, I, I])
op4 = Pauli([I, Z, X, I, I, I])
op5 = Pauli([I, I, Y, Z, I, I])
pau4_e = pauli_complete_algebra([op1, op2, op3, op4, op5], 20)
len(pau4_e)

15

In [46]:
pau4_e

[SuperPauli([(1, Pauli([X, Y, I, I, I, I]))]),
 SuperPauli([(1, Pauli([I, X, Y, I, I, I]))]),
 SuperPauli([(1, Pauli([I, I, X, Y, I, I]))]),
 SuperPauli([(1, Pauli([I, Z, X, I, I, I]))]),
 SuperPauli([(1, Pauli([I, I, Y, Z, I, I]))]),
 SuperPauli([(-2j, Pauli([X, Z, Y, I, I, I]))]),
 SuperPauli([(2j, Pauli([X, X, X, I, I, I]))]),
 SuperPauli([(-2j, Pauli([I, X, Z, Y, I, I]))]),
 SuperPauli([(2j, Pauli([I, Z, Z, Z, I, I]))]),
 SuperPauli([((-4-0j), Pauli([X, Z, Z, Y, I, I]))]),
 SuperPauli([((-4+0j), Pauli([X, X, Z, Z, I, I]))]),
 SuperPauli([((4+0j), Pauli([X, I, Z, I, I, I]))]),
 SuperPauli([(8j, Pauli([X, I, X, Z, I, I]))]),
 SuperPauli([(-8j, Pauli([X, I, Y, Y, I, I]))]),
 SuperPauli([((-16+0j), Pauli([X, I, I, X, I, I]))])]

In [36]:
op1 = Pauli([X, Y, I, I, I, I])
op2 = Pauli([I, X, Y, I, I, I])
op3 = Pauli([I, I, X, Z, I, I])
op4 = Pauli([I, I, Z, X, I, I])
pau4_e = pauli_complete_algebra([op1, op2, op3], 10)
len(pau4_e)

6

In [37]:
pau4_e

[SuperPauli([(1, Pauli([X, Y, I, I, I, I]))]),
 SuperPauli([(1, Pauli([I, X, Y, I, I, I]))]),
 SuperPauli([(1, Pauli([I, I, X, Z, I, I]))]),
 SuperPauli([(-2j, Pauli([X, Z, Y, I, I, I]))]),
 SuperPauli([(-2j, Pauli([I, X, Z, Z, I, I]))]),
 SuperPauli([((-4-0j), Pauli([X, Z, Z, Z, I, I]))])]

In [10]:
op1 = Pauli([X, Y, I, I]) + Pauli([I, I, X, Y])
op2 = Pauli([I, X, Y, I]) + Pauli([Y, I, I, X])
op3 = Pauli([Z, Z, I, I]) + Pauli([I, Z, Z, I]) + Pauli([I, I, Z, Z]) + Pauli([Z, I, I, Z])
pau4 = pauli_complete_algebra([op1, op2, op3], 20)
len(pau4)

13

In [12]:
op1 = Pauli([X, Y, I, I, I]) + Pauli([I, I, X, Y, I]) + Pauli([Y, I, I, I, X])
op2 = Pauli([I, X, Y, I, I]) + Pauli([I, I, I, X, Y])
op3 = Pauli([Z, Z, I, I, I]) + Pauli([I, Z, Z, I, I]) + Pauli([I, I, Z, Z, I]) + Pauli([I, I, I, Z, Z]) + Pauli([Z, I, I, I, Z])
pau5 = pauli_complete_algebra([op1, op2, op3], 500)
len(pau5)

KeyboardInterrupt: 

In [28]:
comm(Pauli([X, Y, I, I]), Pauli([I, X, Y, I]))

SuperPauli([(-2j, Pauli([X, Z, Y, I]))])

In [29]:
comm(Pauli([X, Z, Y, I]), Pauli([I, Z, Z, I]))

SuperPauli([(2j, Pauli([X, I, X, I]))])

In [14]:
n = 4
g1_op1 = z_tensor(n, [0])
for i in range(1, n):
    g1_op1 += z_tensor(n, [i])
g1_op2 = x_tensor(n, [0, 1])
for i in range(1, n):
    g1_op2 += x_tensor(n, [i, (i+1)%n])
g1_op1, g1_op2

(SuperPauli([(1, Pauli([Z, I, I, I])), (1, Pauli([I, Z, I, I])), (1, Pauli([I, I, Z, I])), (1, Pauli([I, I, I, Z]))]),
 SuperPauli([(1, Pauli([X, X, I, I])), (1, Pauli([I, X, X, I])), (1, Pauli([I, I, X, X])), (1, Pauli([X, I, I, X]))]))

In [23]:
pauli_complete_algebra([g1_op1, g1_op2], 11)

[SuperPauli([(1, Pauli([Z, I, I, I])), (1, Pauli([I, Z, I, I])), (1, Pauli([I, I, Z, I])), (1, Pauli([I, I, I, Z]))]),
 SuperPauli([(1, Pauli([X, X, I, I])), (1, Pauli([I, X, X, I])), (1, Pauli([I, I, X, X])), (1, Pauli([X, I, I, X]))]),
 SuperPauli([(2j, Pauli([Y, X, I, I])), (2j, Pauli([Y, I, I, X])), (2j, Pauli([X, Y, I, I])), (2j, Pauli([I, Y, X, I])), (2j, Pauli([I, X, Y, I])), (2j, Pauli([I, I, Y, X])), (2j, Pauli([I, I, X, Y])), (2j, Pauli([X, I, I, Y]))]),
 SuperPauli([((8+0j), Pauli([X, X, I, I])), ((8+0j), Pauli([X, I, I, X])), ((-8+0j), Pauli([Y, Y, I, I])), ((-8+0j), Pauli([Y, I, I, Y])), ((8+0j), Pauli([I, X, X, I])), ((-8+0j), Pauli([I, Y, Y, I])), ((8+0j), Pauli([I, I, X, X])), ((-8+0j), Pauli([I, I, Y, Y]))]),
 SuperPauli([((-8+0j), Pauli([Z, I, I, I])), ((-8+0j), Pauli([Z, X, I, X])), ((-8+0j), Pauli([I, Z, I, I])), ((-8+0j), Pauli([X, Z, X, I])), ((-8+0j), Pauli([I, I, Z, I])), ((-8+0j), Pauli([I, X, Z, X])), ((-8+0j), Pauli([I, I, I, Z])), ((-8+0j), Pauli([X, I, X, Z

In [11]:
len(pauli_complete_algebra([g1_op1, g1_op2], 20, anti=True))

8

In [13]:
pauli_complete_algebra([g1_op1, g1_op2], 20)

[SuperPauli([(1, Pauli([Z, I, I, I])), (1, Pauli([I, Z, I, I])), (1, Pauli([I, I, Z, I])), (1, Pauli([I, I, I, Z]))]),
 SuperPauli([(1, Pauli([X, X, I, I])), (1, Pauli([I, X, X, I])), (1, Pauli([I, I, X, X])), (1, Pauli([X, I, I, X]))]),
 SuperPauli([(2j, Pauli([Y, X, I, I])), (2j, Pauli([Y, I, I, X])), (2j, Pauli([X, Y, I, I])), (2j, Pauli([I, Y, X, I])), (2j, Pauli([I, X, Y, I])), (2j, Pauli([I, I, Y, X])), (2j, Pauli([I, I, X, Y])), (2j, Pauli([X, I, I, Y]))]),
 SuperPauli([((8+0j), Pauli([X, X, I, I])), ((8+0j), Pauli([X, I, I, X])), ((-8+0j), Pauli([Y, Y, I, I])), ((-8+0j), Pauli([Y, I, I, Y])), ((8+0j), Pauli([I, X, X, I])), ((-8+0j), Pauli([I, Y, Y, I])), ((8+0j), Pauli([I, I, X, X])), ((-8+0j), Pauli([I, I, Y, Y]))]),
 SuperPauli([((-8+0j), Pauli([Z, I, I, I])), ((-8+0j), Pauli([Z, X, I, X])), ((-8+0j), Pauli([I, Z, I, I])), ((-8+0j), Pauli([X, Z, X, I])), ((-8+0j), Pauli([I, I, Z, I])), ((-8+0j), Pauli([I, X, Z, X])), ((-8+0j), Pauli([I, I, I, Z])), ((-8+0j), Pauli([X, I, X, Z

In [7]:
pauli_complete_algebra([g1_op1, g1_op2], 20, anti=True)

[SuperPauli([(1, Pauli([Z, I, I, I])), (1, Pauli([I, Z, I, I])), (1, Pauli([I, I, Z, I])), (1, Pauli([I, I, I, Z]))]),
 SuperPauli([(1, Pauli([X, X, I, I])), (1, Pauli([I, X, X, I])), (1, Pauli([I, I, X, X])), (1, Pauli([X, I, I, X]))]),
 SuperPauli([((8+0j), Pauli([I, I, I, I])), ((4+0j), Pauli([Z, Z, I, I])), ((4+0j), Pauli([Z, I, Z, I])), ((4+0j), Pauli([Z, I, I, Z])), ((4+0j), Pauli([I, Z, Z, I])), ((4+0j), Pauli([I, Z, I, Z])), ((4+0j), Pauli([I, I, Z, Z]))]),
 SuperPauli([((2+0j), Pauli([Z, X, X, I])), ((2+0j), Pauli([Z, I, X, X])), ((2+0j), Pauli([I, Z, X, X])), ((2+0j), Pauli([X, Z, I, X])), ((2+0j), Pauli([X, X, Z, I])), ((2+0j), Pauli([X, I, Z, X])), ((2+0j), Pauli([X, X, I, Z])), ((2+0j), Pauli([I, X, X, Z]))]),
 SuperPauli([((8+0j), Pauli([I, I, I, I])), ((8+0j), Pauli([X, I, X, I])), ((8+0j), Pauli([X, X, X, X])), ((8+0j), Pauli([I, X, I, X]))]),
 SuperPauli([((40+0j), Pauli([Z, I, I, I])), ((40+0j), Pauli([I, Z, I, I])), ((40+0j), Pauli([I, I, Z, I])), ((40+0j), Pauli([I,

In [34]:
# set up initial pair of operators for n (> 2) qubits
n = 3
g1_op1 = z_tensor(n, [0])
for i in range(1, n):
    g1_op1 += z_tensor(n, [i])
g1_op2 = x_tensor(n, [0, 1])
for i in range(1, n):
    g1_op2 += x_tensor(n, [i, (i+1)%n])
g1_op1, g1_op2

(SuperPauli([(1, Pauli([Z, I, I])), (1, Pauli([I, Z, I])), (1, Pauli([I, I, Z]))]),
 SuperPauli([(1, Pauli([X, X, I])), (1, Pauli([I, X, X])), (1, Pauli([X, I, X]))]))

In [40]:
n=6
g1_op1 = z_tensor(n, [0])
for i in range(1, n):
    g1_op1 += z_tensor(n, [i])
g1_op2 = x_tensor(n, [0, 1])
for i in range(1, n):
    g1_op2 += x_tensor(n, [i, (i+1)%n])
g1_6 = pauli_complete_algebra([g1_op1, g1_op2], 3*n-1)
len(g1_6)

17

In [42]:
n=10
g1_op1 = z_tensor(n, [0])
for i in range(1, n):
    g1_op1 += z_tensor(n, [i])
g1_op2 = x_tensor(n, [0, 1])
for i in range(1, n):
    g1_op2 += x_tensor(n, [i, (i+1)%n])
g1_10 = pauli_complete_algebra([g1_op1, g1_op2], 3*n-1)
len(g1_10)

29

In [37]:
# time for various n

for n in [3, 4, 5, 6, 10]:
    g1_op1 = z_tensor(n, [0])
    for i in range(1, n):
        g1_op1 += z_tensor(n, [i])
    g1_op2 = x_tensor(n, [0, 1])
    for i in range(1, n):
        g1_op2 += x_tensor(n, [i, (i+1)%n])
    print(f"For n={n}:")
    %timeit pauli_complete_algebra([g1_op1, g1_op2], 3*n-1)

For n=3:
516 ms ± 55.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
For n=4:
2.94 s ± 51.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
For n=5:
12.5 s ± 128 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
For n=6:


KeyboardInterrupt: 

### Task: check find algrebra smaller than complete

In [26]:
# define operators for H: Z1+Z2+Z3, X1X2+X2X3+X3X1
n = 3
ops = [sum([tensor(Z, n, i) for i in range(n)]), sum([tensor(X, n, i)@tensor(X, n, (i+1)%n) for i in range(n)])]

# define opertaor for I: Z1Z3
t = [tensor(Z, 3, 0)@tensor(Z, 3, 2)]

In [27]:
falg = find_algebra(t, ops, 20)
calg = complete_algebra(ops + t, 20)
print(f"calg length = {len(calg)}; falg length = {len(falg)}")

calg length = 18; falg length = 4


### Task: given A, find B such that [A, B] = 0

In [53]:
def find_comm(n):
    # random nxn matrix
    Re = np.random.randn(n, n)
    Im = np.random.randn(n, n)
    A = Re + 1.j * Im

    # find eigenvectors of A tensor A^-T with eigenvalue 1 (some error when finding evals=1 so -1 and allow 1e-6 error about 0)
    L = np.kron(A, np.linalg.inv(A).T)
    l, V = np.linalg.eig(L)
    l -= 1
    l = l.real**2 + l.imag**2
    ii = (l<1e-6)
    v = V[:, ii]

    # construct B by reshape eigenvectors
    for vec in v.T:
        B = vec.reshape(n, n)
        # raise error if AB-BA is not 0
        C = comm(B, A)
        assert np.allclose(C, 0)

    # return the number of Bs found

    return v.shape[1]

In [46]:
[find_comm(i) for i in range(1, 26)]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [52]:
find_comm(2)

[[-0.36960898-0.53607787j  0.11445961-0.84934057j]
 [ 0.93584564-0.85089595j -0.44441963+0.39588458j]]


2

### Task: given A_n, find B such that [A_n, B] = 0 for all n

In [1]:
# helppp not possible...

### Task: decompose a given operator into a sum of Pauli operators (+using Pauli class??)

In [3]:
decomp = decompose(A)
decomp

([0.5, 0.5, -0.5j, 0.5],
 [array([[1., 0.],
         [0., 1.]]),
  array([[0, 1],
         [1, 0]]),
  array([[ 0.+0.j, -0.-1.j],
         [ 0.+1.j,  0.+0.j]]),
  array([[ 1,  0],
         [ 0, -1]])])

In [4]:
np.allclose(decomp[0][0] * I + decomp[0][1] * X + decomp[0][2] * Y + decomp[0][3] * Z, A)

True

In [5]:
test_decomp = tensor(B, 3, 0, 1)
decomp1 = decompose(test_decomp)

In [6]:
tested_decomp = np.zeros(test_decomp.shape)
for i in range(test_decomp.shape[0]**2):
    tested_decomp = tested_decomp + decomp1[0][i] * decomp1[1][i]
np.allclose(tested_decomp, test_decomp)

True