## Constructing Lie Algebras Examples

In [1]:
from Lie_algebras import *
import numpy as np

In [2]:
A = np.array([[1, 0], [1, 0]])
B = np.array([[2, 0], [1, 1]])

In [3]:
complete_algebra([X, I, Z], 5)

[array([[0, 1],
        [1, 0]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[ 1,  0],
        [ 0, -1]]),
 array([[ 0, -2],
        [ 2,  0]])]

In [4]:
find_algebra([X, I], [Z, A, B], 5)

[array([[0, 1],
        [1, 0]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[ 0, -2],
        [ 2,  0]]),
 array([[ 1, -1],
        [ 1, -1]])]

In [5]:
complete_algebra([X, I, comm(X, Z), comm(X, A)], 10)

[array([[0, 1],
        [1, 0]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[ 0, -2],
        [ 2,  0]]),
 array([[ 1, -1],
        [ 1, -1]])]

In [6]:
complete_algebra([X, I], 10) == [X, I]

True

### Tests from paper

##### 1. Lie Algebra g_1

In [24]:
n = 3
ops = [sum([tensor(Z, n, i) for i in range(n)]), sum([tensor(X, n, i)@tensor(X, n, (i+1)%n) for i in range(n)])]

In [8]:
ops

[array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -3.]]),
 array([[0., 0., 0., 1., 0., 1., 1., 0.],
        [0., 0., 1., 0., 1., 0., 0., 1.],
        [0., 1., 0., 0., 1., 0., 0., 1.],
        [1., 0., 0., 0., 0., 1., 1., 0.],
        [0., 1., 1., 0., 0., 0., 0., 1.],
        [1., 0., 0., 1., 0., 0., 1., 0.],
        [1., 0., 0., 1., 0., 1., 0., 0.],
        [0., 1., 1., 0., 1., 0., 0., 0.]])]

In [9]:
alg = complete_algebra(ops, 9)
len(alg)

8

In [10]:
# answers
s_1 = sum([tensor(Z, n, i) for i in range(n)])
s_20 = sum([tensor(X, n, i)@tensor(X, n, i+1) for i in range(n-1)]) + tensor(X, n, n-1)@tensor(X, n, 0)
s_30 = sum([tensor(Y, n, i)@tensor(Y, n, i+1) for i in range(n-1)]) + tensor(Y, n, n-1)@tensor(Y, n, 0)
s_5 = s_1@tensor(Z, n, 0, n-1)

# n=3 case only:
s_21 = tensor(X, 3, 0)@tensor(Z, 3, 1)@tensor(X, 3, 2) + tensor(X, 3, 1)@tensor(Z, 3, 2)@tensor(X, 3, 0) + tensor(X, 3, 2)@tensor(Z, 3, 0)@tensor(X, 3, 1)
s_31 = tensor(Y, 3, 0)@tensor(Z, 3, 1)@tensor(Y, 3, 2) + tensor(Y, 3, 1)@tensor(Z, 3, 2)@tensor(Y, 3, 0) + tensor(Y, 3, 2)@tensor(Z, 3, 0)@tensor(Y, 3, 1)
s_40 = tensor(X, 3, 0)@tensor(Y, 3, 1) + tensor(Y, 3, 0)@tensor(X, 3, 1) + tensor(X, 3, 1)@tensor(Y, 3, 2) + tensor(Y, 3, 1)@tensor(X, 3, 2) + tensor(X, 3, 2)@tensor(Y, 3, 0) + tensor(Y, 3, 2)@tensor(X, 3, 0)
s_41 = tensor(X, 3, 0)@tensor(Z, 3, 1)@tensor(Y, 3, 2) + tensor(Y, 3, 0)@tensor(Z, 3, 1)@tensor(X, 3, 2) + tensor(X, 3, 1)@tensor(Z, 3, 2)@tensor(Y, 3, 0) + tensor(Y, 3, 1)@tensor(Z, 3, 2)@tensor(X, 3, 0) + tensor(X, 3, 2)@tensor(Z, 3, 0)@tensor(Y, 3, 1) + tensor(Y, 3, 2)@tensor(Z, 3, 0)@tensor(X, 3, 1)

In [11]:
# can express any of the solutions in terms of alg
[lin_ind(alg + [i]) for i in [s_1, s_20, s_21, s_20, s_31, s_40, s_41, s_5]]

[False, False, False, False, False, False, False, False]

In [12]:
# can express any of alg in terms of the solutions
[lin_ind([s_1, s_20, s_21, s_20, s_31, s_40, s_41, s_5]+[i]) for i in alg]

[False, False, False, False, False, False, False, False]

In [13]:
# example of the linear relationship between alg and solutions
alg[2] == (2.j*s_40).real

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

##### 3. Lie Algebra g_3

In [14]:
ops2 = [tensor(Z, 3, 0), tensor(Z, 3, 1), tensor(Z, 3, 2), tensor(X, 3, 0)@tensor(X, 3, 1), tensor(X, 3, 1)@tensor(X, 3, 2), tensor(X, 3, 2)@tensor(X, 3, 0)]
4*n**2 - 2*n

30

In [15]:
alg2 = complete_algebra(ops2, 35)
len(alg2)

30

### Limits??

In [16]:
dim = 10
l_op1 = tensor(X, dim, 0, 3)
l_op2 = tensor(Z, dim, 0, 2)
l_op3 = tensor(Y, dim, 0)
l_op1.shape

(1024, 1024)

In [17]:
len(complete_algebra([l_op1+l_op2, l_op2, l_op3 + l_op2], 10))

6

## Experiments for meeting

### Task: check find algrebra smaller than complete

In [26]:
# define operators for H: Z1+Z2+Z3, X1X2+X2X3+X3X1
n = 3
ops = [sum([tensor(Z, n, i) for i in range(n)]), sum([tensor(X, n, i)@tensor(X, n, (i+1)%n) for i in range(n)])]

# define opertaor for I: Z1Z3
t = [tensor(Z, 3, 0)@tensor(Z, 3, 2)]

In [27]:
falg = find_algebra(t, ops, 20)
calg = complete_algebra(ops + t, 20)
print(f"calg length = {len(calg)}; falg length = {len(falg)}")

calg length = 18; falg length = 4


### Task: given A, find B such that [A, B] = 0

In [53]:
def find_comm(n):
    # random nxn matrix
    Re = np.random.randn(n, n)
    Im = np.random.randn(n, n)
    A = Re + 1.j * Im

    # find eigenvectors of A tensor A^-T with eigenvalue 1 (some error when finding evals=1 so -1 and allow 1e-6 error about 0)
    L = np.kron(A, np.linalg.inv(A).T)
    l, V = np.linalg.eig(L)
    l -= 1
    l = l.real**2 + l.imag**2
    ii = (l<1e-6)
    v = V[:, ii]

    # construct B by reshape eigenvectors
    for vec in v.T:
        B = vec.reshape(n, n)
        # raise error if AB-BA is not 0
        C = comm(B, A)
        assert np.allclose(C, 0)

    # return the number of Bs found

    return v.shape[1]

In [46]:
[find_comm(i) for i in range(1, 26)]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [52]:
find_comm(2)

[[-0.36960898-0.53607787j  0.11445961-0.84934057j]
 [ 0.93584564-0.85089595j -0.44441963+0.39588458j]]


2

### Task: given A_n, find B such that [A_n, B] = 0 for all n

### Task: decompose a given operator into a sum of Pauli operators

In [3]:
decomp = decompose(A)
decomp

([0.5, 0.5, -0.5j, 0.5],
 [array([[1., 0.],
         [0., 1.]]),
  array([[0, 1],
         [1, 0]]),
  array([[ 0.+0.j, -0.-1.j],
         [ 0.+1.j,  0.+0.j]]),
  array([[ 1,  0],
         [ 0, -1]])])

In [4]:
np.allclose(decomp[0][0] * I + decomp[0][1] * X + decomp[0][2] * Y + decomp[0][3] * Z, A)

True

In [5]:
test_decomp = tensor(B, 3, 0, 1)
decomp1 = decompose(test_decomp)

In [6]:
tested_decomp = np.zeros(test_decomp.shape)
for i in range(test_decomp.shape[0]**2):
    tested_decomp = tested_decomp + decomp1[0][i] * decomp1[1][i]
np.allclose(tested_decomp, test_decomp)

True

### Task: Pauli class demonstration

In [1]:
import numpy as np
from Lie_algebras import *

In [2]:
p = Pauli([X, Y, I, I, Z])
q = Pauli([Z, Y, I, Y, Y])
r = Pauli([X, X, Y, Y, I])
s = SuperPauli([(2, p), (1, q)])
t = p + 2*q + 3*r

In [21]:
lin_ind([1*p, 1*q, t])

True

In [37]:
%timeit comm(s, t)

2.06 ms ± 68.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
comm(s, t)

SuperPauli([(-12j, Pauli([I, Z, Y, Y, Z]))])

In [12]:
2 * comm(p, p) + 4 * comm(p, q) + 6 * comm(p, r) + comm(q, p) + 2 * comm(q, q) + 3 * comm(q, r)

SuperPauli([(-12j, Pauli([I, Z, Y, Y, Z]))])

In [10]:
acomm(s, t)

SuperPauli([((-10+0j), Pauli([Y, I, I, Y, X])), ((8+0j), Pauli([I, I, I, I, I])), ((6+0j), Pauli([Y, Z, Y, I, Y]))])

In [11]:
2 * acomm(p, p) + 4 * acomm(p, q) + 6 * acomm(p, r) + acomm(q, p) + 2 * acomm(q, q) + 3 * acomm(q, r)

SuperPauli([((8+0j), Pauli([I, I, I, I, I])), ((-10+0j), Pauli([Y, I, I, Y, X])), ((6+0j), Pauli([Y, Z, Y, I, Y]))])