## Constructing Lie Algebras Examples

In [1]:
from Lie_algebras import *
import numpy as np

In [2]:
A = np.array([[1, 0], [1, 0]])
B = np.array([[2, 0], [1, 1]])

In [5]:
complete_algebra([X, I, Z], 4)

[array([[0, 1],
        [1, 0]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[ 1,  0],
        [ 0, -1]]),
 array([[ 0, -2],
        [ 2,  0]])]

In [4]:
find_algebra([X, I], [Z, A, B], 10)

[array([[0, 1],
        [1, 0]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[ 0, -2],
        [ 2,  0]]),
 array([[ 1, -1],
        [ 1, -1]])]

In [5]:
complete_algebra([X, I, comm(X, Z), comm(X, A)], 10)

[array([[0, 1],
        [1, 0]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[ 0, -2],
        [ 2,  0]]),
 array([[ 1, -1],
        [ 1, -1]])]

In [6]:
complete_algebra([X, I], 10) == [X, I]

True

### Tests from paper

##### 1. Lie Algebra g_1

In [151]:
n = 3
ops = [sum([tensor(Z, n, i) for i in range(n)]), sum([tensor(X, n, i)@tensor(X, n, i+1) for i in range(n-1)]) + tensor(X, n, n-1)@tensor(X, n, 0)]

In [152]:
ops

[array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -3.]]),
 array([[0., 0., 0., 1., 0., 1., 1., 0.],
        [0., 0., 1., 0., 1., 0., 0., 1.],
        [0., 1., 0., 0., 1., 0., 0., 1.],
        [1., 0., 0., 0., 0., 1., 1., 0.],
        [0., 1., 1., 0., 0., 0., 0., 1.],
        [1., 0., 0., 1., 0., 0., 1., 0.],
        [1., 0., 0., 1., 0., 1., 0., 0.],
        [0., 1., 1., 0., 1., 0., 0., 0.]])]

In [163]:
alg = complete_algebra(ops, 9)
len(alg)

8

In [169]:
# answers
s_1 = sum([tensor(Z, n, i) for i in range(n)])
s_20 = sum([tensor(X, n, i)@tensor(X, n, i+1) for i in range(n-1)]) + tensor(X, n, n-1)@tensor(X, n, 0)
s_30 = sum([tensor(Y, n, i)@tensor(Y, n, i+1) for i in range(n-1)]) + tensor(Y, n, n-1)@tensor(Y, n, 0)
s_5 = s_1@tensor(Z, n, 0, n-1)

# n=3 case only:
s_21 = tensor(X, 3, 0)@tensor(Z, 3, 1)@tensor(X, 3, 2) + tensor(X, 3, 1)@tensor(Z, 3, 2)@tensor(X, 3, 0) + tensor(X, 3, 2)@tensor(Z, 3, 0)@tensor(X, 3, 1)
s_31 = tensor(Y, 3, 0)@tensor(Z, 3, 1)@tensor(Y, 3, 2) + tensor(Y, 3, 1)@tensor(Z, 3, 2)@tensor(Y, 3, 0) + tensor(Y, 3, 2)@tensor(Z, 3, 0)@tensor(Y, 3, 1)
s_40 = tensor(X, 3, 0)@tensor(Y, 3, 1) + tensor(Y, 3, 0)@tensor(X, 3, 1) + tensor(X, 3, 1)@tensor(Y, 3, 2) + tensor(Y, 3, 1)@tensor(X, 3, 2) + tensor(X, 3, 2)@tensor(Y, 3, 0) + tensor(Y, 3, 2)@tensor(X, 3, 0)
s_41 = tensor(X, 3, 0)@tensor(Z, 3, 1)@tensor(Y, 3, 2) + tensor(Y, 3, 0)@tensor(Z, 3, 1)@tensor(X, 3, 2) + tensor(X, 3, 1)@tensor(Z, 3, 2)@tensor(Y, 3, 0) + tensor(Y, 3, 1)@tensor(Z, 3, 2)@tensor(X, 3, 0) + tensor(X, 3, 2)@tensor(Z, 3, 0)@tensor(Y, 3, 1) + tensor(Y, 3, 2)@tensor(Z, 3, 0)@tensor(X, 3, 1)

In [170]:
# can express any of the solutions in terms of alg
[lin_ind(alg + [i]) for i in [s_1, s_20, s_21, s_20, s_31, s_40, s_41, s_5]]

[False, False, False, False, False, False, False, False]

In [171]:
# can express any of alg in terms of the solutions
[lin_ind([s_1, s_20, s_21, s_20, s_31, s_40, s_41, s_5]+[i]) for i in alg]

[False, False, False, False, False, False, False, False]

In [200]:
# example of the linear relationship between alg and solutions
alg[2] == (2.j*s_40).real

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

##### 3. Lie Algebra g_3

In [155]:
ops2 = [tensor(Z, 3, 0), tensor(Z, 3, 1), tensor(Z, 3, 2), tensor(X, 3, 0)@tensor(X, 3, 1), tensor(X, 3, 1)@tensor(X, 3, 2), tensor(X, 3, 2)@tensor(X, 3, 0)]
4*n**2 - 2*n

30

In [201]:
alg2 = complete_algebra(ops2, 35)
len(alg2)

30

### Limits??

In [222]:
dim = 10
l_op1 = tensor(X, dim, 0, 3)
l_op2 = tensor(Z, dim, 0, 2)
l_op3 = tensor(Y, dim, 0)
l_op1.shape

(1024, 1024)

In [226]:
len(complete_algebra([l_op1+l_op2, l_op2, l_op3 + l_op2], 10))

6